name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你的主分支名称

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Generate index.md
        run: |
          python - <<PYTHON_END
          import os

          with open('index.md', 'w', encoding='utf-8') as f:
              f.write('# 翻译项目\n\n')  # 设置中文标题
              for dirname in os.listdir('.'):
                  if os.path.isdir(dirname):
                      article_path = os.path.join(dirname, 'article.md')
                      if os.path.exists(article_path):
                          title = dirname.replace('-', ' ').title()
                          f.write(f'- [{title}]({article_path})\n')
          PYTHON_END

      - name: Commit index.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update index.md"
          file_pattern: index.md

      - name: Build website
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages  # GitHub Pages 分支名称