name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions

      - name: Generate index.md and mkdocs.yml
        run: |
          cd docs  # 进入 docs 目录
          python - <<PYTHON_END
          import os
          import yaml

          with open('index.md', 'w', encoding='utf-8') as f:
              f.write('# 一些翻译项目\n\n')  # 设置中文标题

          with open('mkdocs.yml.template', 'r', encoding='utf-8') as template_file: # 读取模板文件
              mkdocs_config = yaml.safe_load(template_file)

          nav_items = []
          for dirname in os.listdir('.'):
              if os.path.isdir(dirname) and dirname != '.git':
                  article_path = os.path.join(dirname, 'article.md')
                  if os.path.exists(article_path):
                      title = dirname.replace('-', ' ').title()
                      nav_items.append({title: article_path})
                      with open('index.md', 'a', encoding='utf-8') as f:
                          f.write(f'- [{title}]({article_path})\n')

          mkdocs_config['nav'] = nav_items

          with open('mkdocs.yml', 'w', encoding='utf-8') as outfile: # 在 docs 目录下生成 mkdocs.yml
              yaml.dump(mkdocs_config, outfile, default_flow_style=False, allow_unicode=True)

          PYTHON_END

      - name: Commit index.md and mkdocs.yml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update index.md and mkdocs.yml"
          file_pattern: docs/index.md docs/mkdocs.yml

      - name: Build website
        run: mkdocs build -f docs/mkdocs.yml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4